from typing import Any, Iterator

class Client:
    def __init__(self, firstname: str, lastname: str, address: str, 
                       command: dict[str, int], status: str) -> None: ...
    
    # representation methods
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    
    # integration methods
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __add__(self, other: Client) -> Client: ...
    def __reversed__(self) -> Client: ...
    def __contains__(self, value: Any) -> bool: ...

    # comparaison methods
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def __lt__(self, value: object) -> bool: ...
    def __le__(self, value: object) -> bool: ...
    def __gt__(self, value: object) -> bool: ...
    def __ge__(self, value: object) -> bool: ...

    # bitwise methods
    def __or__(self, value: Any) -> Client: ...
    def __ror__(self, value: Any) -> Client: ...

    # remaining methods
    def __hash__(self) -> int: ...
    def __sizeof__(self) -> int: ...

    # functions
    def len(self) -> int: ...

    def get_firstname(self) -> str: ...
    def get_lastname(self) -> str: ...
    def get_address(self) -> str: ...
    def get_command(self) -> dict[str, int]: ...
    def get_status(self) -> str: ...

    def set_firstname(self, firstname: str) -> None: ...
    def set_lastname(self, lastname: str) -> None: ...
    def set_address(self, address: str) -> None: ...
    def set_command(self, command: dict[str, int]) -> None: ...
    def set_status(self, status: str) -> None: ...