from typing import Iterator, Any, Iterable

class Command:
    def __init__(self, objects_names: Iterable[str], max_objects: Iterable[int],
                       number_of_commands: int) -> None: ...
    
    # representation methods
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    # integration methods
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[dict[str, int]]: ...
    def __add__(self, other: Command) -> Command: ...
    def __reversed__(self) -> Command: ...
    def __contains__(self, value: Any) -> bool: ...

    # comparaison methods
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def __lt__(self, value: object) -> bool: ...
    def __le__(self, value: object) -> bool: ...
    def __gt__(self, value: object) -> bool: ...
    def __ge__(self, value: object) -> bool: ...

    # remaining methods
    def __hash__(self) -> int: ...
    def __sizeof__(self) -> int: ...

    # functions
    def len(self) -> int: ...
    def recreate_commands(self) -> None: ...
    def sub(self) -> dict[str, int] | None: ...