from typing import Iterator

class Distributor:
    def __init__(self, objects_names: tuple[str, ...], time_to_create: float | int,
                       commands: dict[str, int]) -> None: ...
    
    # representation methods
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    # integration methods
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[dict[str, int]]: ...
    def __add__(self, other: Distributor) -> Distributor: ...
    def __reversed__(self) -> Distributor: ...
    def __contains__(self) -> Distributor: ...
    
    # comparaison methods
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...

    # bitwise methods
    def __or__(self, other: Distributor) -> Distributor: ...
    def __ror__(self, other: Distributor) -> Distributor: ...
    
    # other methods
    def __hash__(self) -> int: ...
    def __sizeof__(self) -> int: ...

    # functions
    def len(self) -> int: ...
    
    def do_commands(self) -> None: ...