from typing import Any, Iterator
from ObjectSystem import Object

class Factory:
    def __init__(self, object_name: str | Object, time_to_create: float | int) -> None: ...
    
    # representation methods
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    
    # integration methods
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __add__(self, other: Factory) -> Factory: ...
    def __reversed__(self) -> Factory: ...
    def __contains__(self, value: Any) -> bool: ...

    # comparaison methods
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def __lt__(self, value: object) -> bool: ...
    def __le__(self, value: object) -> bool: ...
    def __gt__(self, value: object) -> bool: ...
    def __ge__(self, value: object) -> bool: ...

    # bitwise methods
    def __or__(self, value: Any) -> Factory: ...
    def __ror__(self, value: Any) -> Factory: ...

    # remaining methods
    def __hash__(self) -> int: ...
    def __sizeof__(self) -> int: ...

    # functions
    def len(self) -> int: ...
    def create(self) -> None: ...