from typing import Any, Iterator

class Object:
    def __init__(self, name: str) -> None: ...
    
    # representation methods
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    
    # integration methods
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __add__(self, other: Object) -> Object: ...
    def __reversed__(self) -> Object: ...
    def __contains__(self, value: Any) -> bool: ...

    # comparaison methods
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def __lt__(self, value: object) -> bool: ...
    def __le__(self, value: object) -> bool: ...
    def __gt__(self, value: object) -> bool: ...
    def __ge__(self, value: object) -> bool: ...

    # bitwise methods
    def __or__(self, value: Any) -> Object: ...
    def __ror__(self, value: Any) -> Object: ...

    # remaining methods
    def __hash__(self) -> int: ...
    def __sizeof__(self) -> int: ...

    # functions
    def len(self) -> int: ...

    def get_name(self) -> str: ...
    def set_name(self, name: str) -> None: ...